### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by Johni0702**
Received this via email.

Have not yet tested it and `tools/build` looks like it should probably go into the webpack config instead.

Not sure we actually need the caching. The browser should cache the HTTP request as long as the webserver is properly configured and JSON decoding it is cheap. Actually, with the cache, what's there to invalidate it should we ever need to updated one of the language files?
Instead we probably want to have webpack manage them, so they're named by hash, only downside is that we always have to load the language code to file mappings, which seems minor.

Note: I do not currently intend to work on this. If anyone wants to do so, feel free to open a new PR based on this one.

### CODE REVIEW

**Comment by Mejans** [comment]
I can help translating into Occitan and French if need be.

**Comment by Fab1en** [comment]
Hi @Johni0702. I have worked on your concerns and fixed it into a new pull request. I don't know if I can make it appear here of if it should be a new pull request.

**Comment by Fab1en** [comment]
By the way, I don't know if this is really the good direction to i18n. As translation is done at launch time by calling `translateEverything`, any text that is not already in the DOM at this time will not be translated. And KnockoutJS mechanism can introduce new element is the DOM at any time, for example : 
```html
<!-- ko if: someExpression -->
    <div>This div is not present in the DOM until someExpression is true</div>
<!-- /ko -->
```
There is not official support for i18n in ko, but I have found some plugins that add this feature : 
* https://github.com/vicary/knockout-i18n is the most promising one
* https://github.com/zewa666/Knockout-i18n
* https://www.i18next.com/ could be used as well ([look at this SO question](https://stackoverflow.com/questions/22760457/how-to-use-knockout-observables-in-i18next))

**Comment by Johni0702** [comment]
While I'm not sure if that direction is good either (I lack experience with I18n), I don't think knockout's mechanisms are much of a problem, as long as knockout is initialized **after** `translateEverything`.
I assumed that's the case but upon looking at it, that doesn't yet appear to be the case.

Things like e.g. https://github.com/Johni0702/mumble-web/blob/8f97d6326cfdafd89995d91b039a568c3a479276/app/index.js#L990-L1011 need manual intervention to be translated either way.

**Pull request merged**
