### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by Fab1en**
This pull request is build on top of the one from @svartoyg.  It fixes two issues raised by @Johni0702 : 
* localization files are now copied to dist via the standard `npm run build` command
* localization information is not cached in localStorage by default. The original behavior can be enabled again via a configuration option

### CODE REVIEW

**Comment by Johni0702** [comment]
Copying the localization files via standard `npm run build` is better (and probably good enough) but what I originally meant was to have webpack copy them (similar to how the css and images are copied).

As is, the browser still has to do a http request each and every load to check if its cache of the language file is up-to-date. Webpack would rename the files to a name which is based on its content, so each time its content changes, its name changes as well and the browser would no longer have to check if it's up-to-date on each load.

I'm not sure if we even want the option to enable the caching. Some people may be tempted to turn it on (cause caching generally sounds like a good idea), unaware that they basically just turned on a bug (cause now they can no longer update language files).

**Comment by svartoyg** [comment]
Am Sonntag, den 12.04.2020, 02:00 -0700 schrieb Jonas Herzig:
> Copying the localization files via standard npm run build is better
> (and probably good enough) but what I originally meant was to have
> webpack copy them (similar to how the css and images are copied).
> 
> As is, the browser still has to do a http request each and every load
> to check if its cache of the language file is up-to-date. Webpack
> would rename the files to a name which is based on its content, so
> each time its content changes, its name changes as well and the
> browser would no longer have to check if it's up-to-date on each
> load.

Yeah, that sounds like the right way to do it. I'm not familiar with
webpack, so i haven't done it that way.


> I'm not sure if we even want the option to enable the caching. Some
> people may be tempted to turn it on (cause caching generally sounds
> like a good idea), unaware that they basically just turned on a bug
> (cause now they can no longer update language files).

Well, usually language files don't change that often. If you take part
in an audio conference, you might need to reload the page from time to
time and then it would be a bit annoying to load the files from the
server every time. Even if the content has changed: It's is not that
crucial to have the latest version.

I could extend the cache implementation with a time-to-live feature, so
that the cached values get invalidated after, e.g. 2 days.

**Comment by Johni0702** [comment]
> I'm not familiar with webpack, so i haven't done it that way.

Yeah, that's fair. I recall spending quite a bit of time until I got webpack to do exactly what I wanted it to do.

I don't think there's any need to add any kind of TTL to the cache implementation. We're sort of re-inventing the wheel there anyway: HTTP already has support for caching stuff, with TTL or with up-to-date check or indefinitely.
All we gotta do to take optimal advantage of it is to get webpack to rename the file to have a content-based name (and the choose the indefinitely option).

Even if @Fab1en doesn't want to spend the time to do that, I'd be fine with merging this PR as is (well, almost, https://github.com/Johni0702/mumble-web/pull/78#issuecomment-612586890 needs fixing first).

**Comment by Mejans** [comment]
fr.json would be:
`{
  "connectdialog.title": "Connexion au serveur",
  "connectdialog.address": "Adresse",
  "connectdialog.port": "Port",
  "connectdialog.username": "Nom d’utilisateur",
  "connectdialog.password": "Mot de passe",
  "connectdialog.tokens": "Jetons",
  "connectdialog.remove": "Supprimer",
  "connectdialog.add": "Ajouter",
  "connectdialog.cancel": "Annuler",
  "connectdialog.connect": "Se connecter"
}`

oc.json would be:
`{
  "connectdialog.title": "Connexion al servidor",
  "connectdialog.address": "Adreça",
  "connectdialog.port": "Pòrt",
  "connectdialog.username": "Nom d’utilizaire",
  "connectdialog.password": "Senhal",
  "connectdialog.tokens": "Getons",
  "connectdialog.remove": "Suprimir",
  "connectdialog.add": "Ajustar",
  "connectdialog.cancel": "Anullar",
  "connectdialog.connect": "Se connectar"
}`

My 50cent :)

**Comment by Johni0702** [comment]
Closing in favour of the webpack variant: https://github.com/Johni0702/mumble-web/commit/0ca2a45358b1fc66c1dc7ef4443049b7c8240d52

**Pull request closed without merging**
